import { prisma } from "@/lib/db";
import { v4 as uuidv4 } from "uuid";

export class ComplianceMetricService {

    /**
     * Records a masking event (firewall triggered).
     */
    async recordMaskingEvent(teamId: string, tokensMasked: number) {
        // In a real metrics DB (e.g. Timescale/Clickhouse), this would be an insert
        // Here we can use a Counter model or just Log
        await (prisma as any).agentLog.create({
            data: {
                // id field is auto-generated by UUID in schema usually, but if needed:
                id: uuidv4(),
                taskId: "SYSTEM_METRIC", // Global system log
                type: "COMPLIANCE_MASK",
                content: JSON.stringify({ teamId, tokensMasked, timestamp: new Date() }),
                stepNumber: 0
            }
        });
    }

    /**
     * Returns the "Compliance Scorecard" for the dashboard.
     */
    async getComplianceScorecard(_teamId: string) {
        try {
            // Count PII tokens from all ScrapingJobs (Filtered by Team)
            const jobs = await prisma.scrapingJob.findMany({
                where: { 
                    teamId: _teamId,
                    tokenMap: { not: {} } 
                },
                select: { tokenMap: true }
            });

            let maskedCount = 0;
            for (const job of jobs) {
                if (job.tokenMap && typeof job.tokenMap === 'object') {
                    maskedCount += Object.keys(job.tokenMap).length;
                }
            }

            // Add a base number to simulate historical data if count is low (for demo continuity)
            const displayCount = maskedCount > 0 ? maskedCount : 0;

            // Human Verifications could be the number of "Identity Reveals" or "Manual Reviews"
            // Let's count ManualReview records if they exist, or just use 0
            const manualReviews = await prisma.manualReview.count();

            // Calculate "Saved Liability" based on industry benchmarks (Configurable)
            // Avg data breach cost per record is ~$160-$200 according to IBM/Ponemon.
            // We use a high-risk sector baseline ($500) if not configured.
            const LIABILITY_MULTIPLIER = Number(process.env['COMPLIANCE_LIABILITY_PER_RECORD']) || 165;
            const savedLiability = displayCount * LIABILITY_MULTIPLIER;

            return {
                piiProtected: displayCount,
                humanVerifications: manualReviews,
                estimatedLiabilitySavedUSD: savedLiability,
                complianceStatus: "ASSISTED_MODE_ACTIVE"
            };
        } catch (error) {
            console.error("Failed to calculate compliance scorecard", error);
            return {
                piiProtected: 0,
                humanVerifications: 0,
                estimatedLiabilitySavedUSD: 0,
                complianceStatus: "ERROR"
            };
        }
    }
}

export const complianceService = new ComplianceMetricService();
